### PR TITLE
Initial tests for market.protocol

### PR DESCRIPTION
**Pull request by tomgalloway**

### CODE REVIEW

**Comment by cpacia** [comment]
Nice

**Comment by tcharding** [comment]
These tests are awesome. I had no idea how to start testing market/, you are paving the way, good effort tomgalloway.

**Comment by tomgalloway** [comment]
:) market/profile methods are nearly complete for basic testing.

**Comment by tomgalloway** [comment]
@cpacia - Please can you review these changes with a view to merging them in?

**Comment by tcharding** [comment]
I think OB1 (that includes Chris) are all AFK at the moment in Belgium

**Comment by hoffmabc** [comment]
Yes sorry @tomgalloway we will try to take a look at these tomorrow once we are all back and recovered from Amsterdam. Thanks for the contribution!

**Comment by cpacia** [comment]
@tomgalloway is this ready to merge or do you plan on adding more?

**Comment by tomgalloway** [comment]
@cpacia yeah this is a good spot to merge before I start work on tests for one of the other market files.

**Pull request merged**
