### PR TITLE
Modified startup procedure

### PR DESCRIPTION
**Pull request by tcharding**
This  is the re-write of previous idea to remove the need to pass the database around. It also adds the ability for command line options to override config file options. Also all constants are in one place so no need to pass TESTNET and various other constants around either. 

This patch is not a merge candidate. Not rebased but does include some changes (i.e HEARTBEAT) so I could get it to run. Has bugs :)

### CODE REVIEW

**Comment by tcharding** [comment]
Following on from discussion in Slack re: using systemd (and launchd) to daemonize OB. This patch has daemonize() removed. Also configuration file hierarchy with command line options override is functional. Could this please be marked as 'in progress'?

**Comment by ac225519** [comment]
I never used the build in daemonize function.
Not flexible enough.
This is how I do it:
# start node with low priority/high nice and no 'nohup.out' file
 nohup nice -n 19 ./start-openbazaar-node "$@" >/dev/null 2>&1 &
 # wrong place Chris. Should be /var/run/
 sleep 2 ; ps -xa | grep -se "ob_python ./openbazaard.p[y]" | awk '{print $1}' >/tmp/openbazaard.pid
# $! does not work
# you can watch the output of the Server/Node with:  less +F -S OpenBazaar-Server/obdata/debug.log

**Comment by cpacia** [comment]
My one issue here is I wouldn't put the main code in daemon.py. The program isn't always run as daemon so it's kind of weird to have the core code in that module.

**Comment by tcharding** [comment]
I agree, I didn't want to go changing the file names on you as well as a solid refactor. I'm still coming to terms with constants.py changing to config.py (and yes I did rename it constants in one of my dev branches thinking I had accidentally changed it myself). I'll go ahead and rename them mercil

**Comment by tcharding** [comment]
On the same topic, can I consolidate all the utils directories into one utils in the root directory?

**Pull request closed without merging**
