### PR TITLE
Add chdir functionality.

### PR DESCRIPTION
**Pull request by hoffmabc**
This fixes a problem finding the ob.cfg file on startup.

### CODE REVIEW

**Comment by cpacia** [comment]
Is this ok to merge or are you still working on it?

**Comment by hoffmabc** [comment]
It failed so let me clean it up.

**Comment by cpacia** [comment]
Well it probably failed because of that problem with travis. Which I can't figure out.

**Comment by hoffmabc** [comment]
Yeah totally forgot about that. LGTM.

**Pull request merged**
