### PR TITLE
Move loading of bitcoin prices into a background thread on a 15 minute interval

### PR DESCRIPTION
**Pull request by ddustin**
@cpacia

### CODE REVIEW

**Comment by cpacia** [comment]
Looks good. Next you just want get a list of backup APIs to call in case bitcoinaverage is down. @jjeffryes do you have the other APIs you used somewhere?

**Comment by jjeffryes** [comment]
@cpacia you can looks at js/utils/getBitcoinPrice.js to see how the client is doing it. 

The APIs being called are 
- https://blockchain.info/ticker
- https://api.coinkite.com/public/rates
- https://api.bitcoinaverage.com/all
- http://api.bitcoincharts.com/v1/weighted_prices.json

**Comment by ddustin** [comment]
@cpacia I implemented the backup APIs and added test coverage -- should be ready for your review again.

**Comment by cpacia** [comment]
Looks good. I'll test it out and merge tomorrow.

**Pull request merged**
