### PR TITLE
SMTP Notifications

### PR DESCRIPTION
**Pull request by hoffmabc**
These notifications are enabled:

* Someone follows you (once per node)
* Order received (Vendor)
* Order funded (Vendor)
* Order confirmed/shipped (Buyer)
* Rating received (Vendor)
* Dispute opened
* Dispute resolved
* Order refunded (Buyer)

### CODE REVIEW

**Comment by hoffmabc** [comment]
@morebrownies would like some feedback on email contents here.

**Comment by hoffmabc** [comment]
@cpacia can you please review?

**Comment by morebrownies** [comment]
@hoffmabc I just noticed you wanted me to review the content of the emails. The link above appears to be dead, can you point me in the right direction?

**Comment by hoffmabc** [comment]
https://github.com/OpenBazaar/OpenBazaar-Server/pull/367/files

Just look for the words smtpnotification.send

**Comment by cpacia** [comment]
@hoffmabc can you change this to migration 4. Migration 3 is get_followers.

**Comment by Derrick-** [comment]
I know I'm a day late on this, but would you consider whther this isn't a feature more appropriate for a client than a server. Email notifications from the server really feels like bloat to me.

What is the role of the server, and of the client?

**Comment by hoffmabc** [comment]
I don't believe this is bloat. Why would a client be responsible for this? Clients are thin UIs to the API. That's like if your Dropbox app sent email notifications rather than Dropbox's server. Or am I missing something?

**Comment by hoffmabc** [comment]
You can think of the server as the web server here and your client as the app a user would install.

**Comment by Derrick-** [comment]
I think perhaps would be a better separation of concerns to have the email notification in at least a separate module/plugin that could poll and aggregate the emails. I guess I do agree with you on the client, it should stay thin; but i feel the same about the OB Server, I would really like to see it's concerns remain limited.

I think it's a great feature. I just thought the question should get out there. Thanks for your service.

**Comment by mariodian** [comment]
Is server checking whether I'm currently using the client (I'm online)? I shouldn't be getting email notifications while using the client, because I see notifications in the upper right corner of the app.

**Comment by morebrownies** [comment]
That sounds more like a user choice to me. Some users may want to get every notification in their email so that they have a second copy of it. And some may want exactly what you described @mariodian 

I'm going to work on designs for a Notifications tab in settings that gives more control to the user on how they want notifications to work.

**Comment by mariodian** [comment]
Yes, having the choice is always good, thanks! 

Btw I think a user should also be able to choose what kind of notifications he's interested in. For example I only need emails about new order, dispute and a chat message. Mostly notifications that requires an immediate action.

**Comment by jjeffryes** [comment]
Allowing the user greater control over notifications is definitely on our roadmap.

**Comment by sashamd** [comment]
Email on chat message would be great.

**Comment by hoffmabc** [comment]
This is better served through webhooks since it's pretty annoying to get emails for every chat message. Webhooks would provide the ability to run through ifttt or some other service to then send to email of you wanted.

**Comment by sashamd** [comment]
Thanks for quick answer.
I have thought about Websocket API as well.
I agree it's annoying but it also allows for instant reaction to messages.

**Comment by sashamd** [comment]
For now will do every five minutes:
curl -k --data "username=username&password=password" --dump-header headers https://localhost:18469/api/v1/login
 curl -k -L -b headers https://localhost:18469/api/v1/get_chat_conversations.
Thanks again.

**Comment by hoffmabc** [comment]
Great to hear you came up with a solution.

**Pull request merged**
