### PR TITLE
File Config for constants.py

### PR DESCRIPTION
**Pull request by teamcreed**
New file config ob.cfg for constants.py , the file constants.py was rewritten, constants.py now can be loaded from a config file. made by "foxcarlos@gmail.com" of TeamCreed

### CODE REVIEW

**Comment by teamcreed** [comment]
Fixed bug

**Comment by teamcreed** [comment]
Fixed bug

**Comment by hoffmabc** [comment]
Just make sure to fix the Travis errors.

**Comment by cpacia** [comment]
Yeah run make locally and see what errors it spits out. Mostly just formatting stuff. I'll test it out today.

**Comment by hoffmabc** [comment]
This will be a nice update.

**Comment by hoffmabc** [comment]
@foxcarlos need to revise the merge issues before we can move forward. Can you please rebase it?

**Comment by teamcreed** [comment]
Ok. thank you @hoffmabc

**Pull request merged**
