### PR TITLE
add pylint to requirements

### PR DESCRIPTION
**Pull request by insanity54**

### CODE REVIEW

**Comment by cpacia** [comment]
We have a requirement.txt. Do we think it's needed in the main requirements? I know the readme says to run make but that's really only to run the tests.

**Comment by hoffmabc** [comment]
Then we need a requirements_test.txt for testing related packages.

**Comment by cpacia** [comment]
That's what I meant. You already put that in there @brian

**Comment by hoffmabc** [comment]
Ok then I'm a genius. @insanity54 do you mind pulling pylint and leave requests.

**Comment by cryptid11** [comment]
problem persists...

**Pull request closed without merging**
