### PR TITLE
Added unit tests to db/tests/test_datastore

### PR DESCRIPTION
**Pull request by tcharding**
This brings coverage upto 95%

### CODE REVIEW

**Comment by tcharding** [comment]
Build fails during 'pip install'. Do I need to action this?

**Comment by cpacia** [comment]
It failed because brian deleted txrudp 0.5.0 from pypi by accident. If you bump it to 0.5.1 it should run ok.

**Comment by cpacia** [comment]
On a side note, I'm currently adding some more stuff to this file in the PR I'm working on. You might want to rebase after I merge that.

It's a small change to Messages and added and new Cases class.

**Comment by tcharding** [comment]
So, to clarify. I should wait till you merge then rebase and re-submit the pull request?

**Pull request closed without merging**
