### PR TITLE
Add sqlite3 to requirements.txt

### PR DESCRIPTION
**Pull request by teran-mckinney**

### CODE REVIEW

**Comment by cpacia** [comment]
sqlite3 should be part of the standard library no?

**Comment by teran-mckinney** [comment]
I think on most systems it is. For mine, I had to install pysqlite for it to build (FreeBSD). I don't know if it will hurt or not having it there.

**Comment by unsystemizer** [comment]
When there is no officially supported OS & version (such as Ubuntu 14.04 LTS), the list of "requirements" can keep growing *ad infinitium*. 
I've asked several times for this decision, but officially the s/w is still targeted at all Unix-like OS so there will always be someone whose OS will miss this or that package.

**Comment by hoffmabc** [comment]
The answer is that we will officially support Ubuntu 12.x and Ubuntu 14.x for the release meaning those are the two releases we will heavily test and ensure correct functionality on. We may extend that at some point in time but that is the plan for now. If people submit patches that enable other OSs while not interfering with those supported systems we will evaluate and accept them.

**Pull request closed without merging**
